### ISSUE TITLE
Store event data as JSON

### ISSUE THREAD

**Issue by SamuelLundmark** [LendoSTPGdansk/lendo-infrastructure-bundle#143]
You should be able to store the event without the whole event class in the data column.

**Right now:**
```
    private static function pack($data)
    {
        return base64_encode(gzcompress(serialize($data)));
    }
    private static function unpack($data)
    {
        return unserialize(gzuncompress(base64_decode($data)));
    }
```

**Store the event data as json:**
```

    private static function pack($data)
    {
        return base64_encode(json_encode($data));
    }
    private static function unpack($data)
    {
        return json_decode(base64_decode($data));
    }
```

**Comment by ulff** [comment]
That cannot be made with just changing that implementation. Currently we just pack and unpack the object, not recreate it. Serializing is letting us instantiate the object without any mapping information. 

If we implement it the way defined above, we should make implementation of creating object instances from the json structure. And that means implementing in all of the services, for all of events something like we have in projections - custom methods for json'izing and de-json'izing objects. So it is definitely bigger task, regarding number of changes.

So the question is should we proceed with that? What is the purpose of that task? Is using PHP's serialization methods something we need to definitely abandon, even if it requires a lot of work now?

**Comment by kristofferingemansson** [comment]
@SamuelLundmark I don't think we need the base64-encode/decode since json-encode/decode already takes care of encoding any binary data?

```
    private static function pack($data)
    {
        return json_encode($data);
    }
    private static function unpack($data)
    {
        return json_decode($data);
    }
```
